#!/bin/bash

############################################# 
# Mehmet Çalık tarafından yapılmıştır.      #
# Eposta : mcalik558@gmail.com              #
#############################################

#  Bu script GNU Lesser General Public License v3.0 ile lisanslanmıştır.

# https://sulincix.gitlab.io/sayfalar/html/debian-iso-yapimi.html adresinden uyarlanmıştır.

gri=$'\e[1;30m';
kirmizi=$'\e[1;31m';
yesil=$'\e[1;32m';
sari=$'\e[1;33m';
mavi=$'\e[1;34m';
mor=$'\e[1;35m';
turkuaz=$'\e[1;36m';
sifirla=$'\e[0m';
kalin=$'\e[1m';

if [[ "$(whoami)" != root ]]; then
	echo "${kirmizi}İlk Önce Root Olmanız Gerekmekte.."
	exit 0
fi

clear
echo "${yesil}</> ${kirmizi}Bağlanmış dosyalar ayrılıyor.. ${yesil}</> ${turkuaz}"
umount -lf -R debian-chroot/* 2>/dev/null
echo "${yesil}</> ${kirmizi}Temizleme işlemi.. ${yesil}</> ${turkuaz}"
chroot debian-chroot apt autoremove
chroot debian-chroot apt clean
rm -f debian-chroot/root/.bash_history
rm -rf debian-chroot/var/lib/apt/lists/*
find debian-chroot/var/log/ -type f | xargs rm -f
echo "${yesil}</> ${kirmizi}Paketleme aşaması.. ${yesil}</> ${turkuaz}"
mkdir isowork
mksquashfs debian-chroot filesystem.squashfs -comp gzip -wildcards
mkdir -p isowork/live
mv filesystem.squashfs isowork/live/filesystem.squashfs
echo "${yesil}</> ${kirmizi}vmlinuz ve initrd dosyalarını isowork/live içerisine atalım. ${yesil}</> ${turkuaz}"
cp -pf debian-chroot/boot/initrd.img* isowork/live/initrd.img
cp -pf debian-chroot/boot/vmlinuz* isowork/live/vmlinuz
echo "${yesil}</> ${kirmizi}grub.cfg dosyası oluşturalım. ${yesil}</> ${turkuaz}"
mkdir -p isowork/boot/grub/
echo 'insmod all_video' > isowork/boot/grub/grub.cfg
echo 'menuentry "Start Debian Unofficial 64-bit" --class debian {' >> isowork/boot/grub/grub.cfg
echo '    linux /live/vmlinuz boot=live live-config live-media-path=/live --' >> isowork/boot/grub/grub.cfg
echo '    initrd /live/initrd.img' >> isowork/boot/grub/grub.cfg
echo '}' >> isowork/boot/grub/grub.cfg
echo "${yesil}</> ${kirmizi}İso oluşturuluyor.. ${yesil}</> ${turkuaz}"
grub-mkrescue isowork -o debian-live.iso
echo "${yesil}</> ${kirmizi}Sorun Var ise: mcalik558@gmail.com${yesil}</> ${turkuaz}"
