#!/bin/bash

############################################# 
# Mehmet Çalık tarafından yapılmıştır.      #
# Eposta : mcalik558@gmail.com              #
#############################################

# Bu script GNU Lesser General Public License v3.0 ile lisanslanmıştır.

# https://sulincix.gitlab.io/sayfalar/html/debian-iso-yapimi.html adresinden uyarlanmıştır.

gri=$'\e[1;30m';
kirmizi=$'\e[1;31m';
yesil=$'\e[1;32m';
sari=$'\e[1;33m';
mavi=$'\e[1;34m';
mor=$'\e[1;35m';
turkuaz=$'\e[1;36m';
sifirla=$'\e[0m';
kalin=$'\e[1m';


if [[ "$(whoami)" != root ]]; then
	echo "${kirmizi}Önce sudo su komutu ile root olmalısınız!!!.."
	exit 0
fi

clear
echo "${yesil}</> ${kirmizi}Gerekli Paketler Yükleniyor ${yesil}</>"
echo "${yesil}</> ${kirmizi}Yüklenecek Paketler : debootstrap xorriso squashfs-tools mtools grub-pc-bin grub-efi devscripts nano${yesil} </> ${turkuaz}"
apt install debootstrap xorriso squashfs-tools mtools grub-pc-bin grub-efi devscripts git nano
echo "${yesil}</> ${kirmizi} debian-chroot adlı dosya oluşturulup, debian'nın temeli bu dosyaya atılacak.. ${yesil}</> ${turkuaz}"
mkdir debian-chroot
chown root debian-chroot
debootstrap --arch=amd64 --no-merged-usr sid debian-chroot https://deb.debian.org/debian
echo "${yesil}</> ${kirmizi}Temel atıldı. içeriğe giriş yapılıp kernel driver vb yüklenecek.. ${yesil}</> ${turkuaz}"
for i in dev dev/pts proc sys; do mount -o bind /$i debian-chroot/$i; done
echo 'deb http://deb.debian.org/debian sid main contrib non-free' > debian-chroot/etc/apt/sources.list
chroot debian-chroot apt update
chroot debian-chroot apt install linux-image-amd64 -y
chroot debian-chroot apt install grub-pc-bin grub-efi-ia32-bin grub-efi -y
chroot debian-chroot apt install live-config live-boot -y 
chroot debian-chroot apt install xorg xinit -y
chroot debian-chroot apt install atmel-firmware bluez-firmware dahdi-firmware-nonfree \
  firmware-amd-graphics firmware-ath9k-htc firmware-atheros \
  firmware-b43-installer firmware-b43legacy-installer firmware-bnx2 \
  firmware-bnx2x firmware-brcm80211 firmware-cavium \
  firmware-intel-sound firmware-intelwimax firmware-ipw2x00 \
  firmware-ivtv firmware-iwlwifi firmware-libertas \
  firmware-linux firmware-linux-free firmware-linux-nonfree \
  firmware-misc-nonfree firmware-myricom firmware-netronome \
  firmware-netxen firmware-qcom-soc firmware-qlogic \
  firmware-realtek firmware-samsung firmware-siano \
  firmware-sof-signed firmware-ti-connectivity firmware-zd1211 hdmi2usb-fx2-firmware -y
echo "${yesil}</> ${kirmizi} <- - -> Lütfen Dikkatlice okuyunuz <- - ->   ${yesil}</>"
echo "${yesil}</> ${kirmizi}Temel atıldı. Şimdi masaüstü ortamı ve istediğin uygulamaları kur. İşin bitince exit komutu ile çık ve ./isoolustur komutunu çalıştır..${yesil}</>"
chroot debian-chroot /bin/bash
