#!/bin/bash

############################################# 
# Mehmet Çalık tarafından yapılmıştır.      #
# Eposta : mcalik558@gmail.com              #
#############################################

# Bu script GNU Lesser General Public License v3.0 ile lisanslanmıştır.

# https://sulincix.gitlab.io/sayfalar/html/debian-iso-yapimi.html adresinden uyarlanmıştır.

gri=$'\e[1;30m';
kirmizi=$'\e[1;31m';
yesil=$'\e[1;32m';
sari=$'\e[1;33m';
mavi=$'\e[1;34m';
mor=$'\e[1;35m';
turkuaz=$'\e[1;36m';
sifirla=$'\e[0m';
kalin=$'\e[1m';


if [[ "$(whoami)" != root ]]; then
	echo "${kirmizi}Önce sudo su komutu ile root olmalısınız!!!.."
	exit 0
fi

clear
echo "${yesil}</> ${kirmizi}Gerekli Paketler Yükleniyor ${yesil}</>"
echo "${yesil}</> ${kirmizi}Yüklenecek Paketler : debootstrap xorriso squashfs-tools mtools grub-pc-bin grub-efi devscripts nano${yesil} </> ${turkuaz}"

sudo apt install debootstrap xorriso squashfs-tools mtools grub-pc-bin grub-efi devscripts git nano

echo "${yesil}</> ${kirmizi} debian-chroot adlı dosya oluşturulup, debian'nın temeli bu dosyaya atılacak.. ${yesil}</> ${turkuaz}"


mkdir debian-chroot
sudo chown root debian-chroot
sudo debootstrap --arch amd64 --no-merged-usr sid debian-chroot https://ftp.debian.org/debian


echo "${yesil}</> ${kirmizi}Temel atıldı. içeriğe giriş yapılıp kernel driver vb yüklenecek.. ${yesil}</> ${turkuaz}"
for i in dev dev/pts proc sys; do sudo mount -o bind /$i debian-chroot/$i; done
echo 'deb http://deb.debian.org/debian sid main contrib non-free' > debian-chroot/etc/apt/sources.list

sudo chroot debian-chroot apt update

sudo chroot debian-chroot apt install linux-image-amd64 -y
sudo chroot debian-chroot apt install grub-pc-bin grub-efi-ia32-bin grub-efi -y
sudo chroot debian-chroot apt install live-config live-boot -y 
sudo chroot debian-chroot apt install xorg xinit -y
sudo chroot debian-chroot apt install atmel-firmware bluez-firmware dahdi-firmware-nonfree -y
sudo chroot debian-chroot apt install firmware-amd-graphics firmware-ath9k-htc firmware-atheros -y
sudo chroot debian-chroot apt install firmware-b43-installer firmware-b43legacy-installer firmware-bnx2 -y
sudo chroot debian-chroot apt install firmware-bnx2x firmware-brcm80211 firmware-cavium -y
sudo chroot debian-chroot apt install firmware-intel-sound firmware-intelwimax firmware-ipw2x00 -y
sudo chroot debian-chroot apt install firmware-ivtv firmware-iwlwifi firmware-libertas -y
sudo chroot debian-chroot apt install firmware-linux firmware-linux-free firmware-linux-nonfree -y
sudo chroot debian-chroot apt install firmware-misc-nonfree firmware-myricom firmware-netronome -y
sudo chroot debian-chroot apt install firmware-netxen firmware-qcom-soc firmware-qlogic -y
sudo chroot debian-chroot apt install firmware-realtek firmware-samsung firmware-siano -y
sudo chroot debian-chroot apt install firmware-sof-signed firmware-ti-connectivity firmware-zd1211 hdmi2usb-fx2-firmware -y

sudo chroot debian-chroot /bin/bash -c "apt-get update && apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc && mkdir -p /usr/src && cd /usr/src && git clone https://github.com/xanmod/linux.git && cd linux && git checkout xanmod && make localmodconfig && make -j$(nproc) && make modules_install && make install"

sudo chroot debian-chroot apt install kde-full -y
sudo chroot debian-chroot update-grub
sudo chroot debian-chroot grub-install

echo "${yesil}</> ${kirmizi} <- - -> Lütfen Dikkatlice okuyunuz <- - ->   ${yesil}</>"
echo "${yesil}</> ${kirmizi}Temel atıldı. Şimdi masaüstü ortamı ve istediğin uygulamaları kur. İşin bitince exit komutu ile çık ve ./isoolustur komutunu çalıştır..${yesil}</>"

sudo chroot debian-chroot /bin/bash
